### ISSUE TITLE
Bug: The following IntegerDivisionByZeroException was thrown building AnimatedBuilder: IntegerDivisionByZeroException

### ISSUE THREAD

**Issue by julianfrancodev** [TheAnkurPanchani/card_swiper#15]
**Hello there this error happens when try to load network resources** 

_More details here:_ 

```
When the exception was thrown, this was the stack: 
#0      int.% (dart:core-patch/integers.dart:45:7)
#1      _CustomLayoutStateBase._buildAnimation (package:card_swiper/src/custom_layout.dart:98:29)
#2      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1519:19)
#3      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:174:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3422:20)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#21     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#25     _invoke (dart:ui/hooks.dart:166:10)
#26     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#27     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

```

**Comment by TheAnkurPanchani** [comment]
Please provide some code to replicate the issue.
