### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by woyl** [TheAnkurPanchani/card_swiper#99]
E/flutter ( 1104): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 1104): #0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:262:53)
E/flutter ( 1104): #1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:387:19)
E/flutter ( 1104): #2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:200:16)
E/flutter ( 1104): #3      _TransformerPageViewState.onChangeNotifier (package:card_swiper/src/transformer_page_view/transformer_page_view.dart:583:14)
E/flutter ( 1104): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
E/flutter ( 1104): #5      IndexController.next (package:card_swiper/src/transformer_page_view/index_controller.dart:110:5)
E/flutter ( 1104): #6      _SwiperTimerMixin._onTimer (package:card_swiper/src/swiper.dart:391:24)
E/flutter ( 1104): #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 1104): #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 1104): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

**Comment by Nuyoahhjh** [comment]
E/flutter ( 3362): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 3362): #0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:260:53)
E/flutter ( 3362): #1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:381:19)
E/flutter ( 3362): #2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:198:16)
E/flutter ( 3362): #3      _TransformerPageViewState.onChangeNotifier (package:card_swiper/src/transformer_page_view/transformer_page_view.dart:583:14)
E/flutter ( 3362): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
E/flutter ( 3362): #5      IndexController.next (package:card_swiper/src/transformer_page_view/index_controller.dart:110:5)
E/flutter ( 3362): #6      _SwiperTimerMixin._onTimer (package:card_swiper/src/swiper.dart:391:24)
E/flutter ( 3362): #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 3362): #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 3362): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by kavin-zhihua** [comment]
出错堆栈

0	#0 ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:260)
1	#1 _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:381)
2	#2 PageController.animateToPage (package:flutter/src/widgets/page_view.dart:198)
3	#3 _TransformerPageViewState.onChangeNotifier (package:card_swiper/src/transformer_page_view/transformer_page_view.dart:583)
4	#4 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433)
5	#5 IndexController.next (package:card_swiper/src/transformer_page_view/index_controller.dart:110)
6	#6 _SwiperTimerMixin._onTimer (package:card_swiper/src/swiper.dart:391)
7	#7 _rootRunUnary (dart:async/zone.dart:1407)
8	#8 _CustomZone.runUnary (dart:async/zone.dart:1308)
9	#9 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
10	#10 _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1254)
11	#11 _rootRunUnary (dart:async/zone.dart:1415)
12	#12 _CustomZone.runUnary (dart:async/zone.dart:1308)
13	#13 _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1238)
14	#14 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
15	#15 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
16	#16 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by kavin-zhihua** [comment]
> E/flutter ( 3362): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value E/flutter ( 3362): #0 ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:260:53) E/flutter ( 3362): [#1](https://github.com/TheAnkurPanchani/card_swiper/issues/1) _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:381:19) E/flutter ( 3362): [#2](https://github.com/TheAnkurPanchani/card_swiper/issues/2) PageController.animateToPage (package:flutter/src/widgets/page_view.dart:198:16) E/flutter ( 3362): [#3](https://github.com/TheAnkurPanchani/card_swiper/issues/3) _TransformerPageViewState.onChangeNotifier (package:card_swiper/src/transformer_page_view/transformer_page_view.dart:583:14) E/flutter ( 3362): [#4](https://github.com/TheAnkurPanchani/card_swiper/issues/4) ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24) E/flutter ( 3362): [#5](https://github.com/TheAnkurPanchani/card_swiper/issues/5) IndexController.next (package:card_swiper/src/transformer_page_view/index_controller.dart:110:5) E/flutter ( 3362): [#6](https://github.com/TheAnkurPanchani/card_swiper/issues/6) _SwiperTimerMixin._onTimer (package:card_swiper/src/swiper.dart:391:24) E/flutter ( 3362): [#7](https://github.com/TheAnkurPanchani/card_swiper/issues/7) _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19) E/flutter ( 3362): [#8](https://github.com/TheAnkurPanchani/card_swiper/pull/8) _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5) E/flutter ( 3362): [#9](https://github.com/TheAnkurPanchani/card_swiper/issues/9) _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Did you solve it?
